### ISSUE TITLE
Master to-do list

### ISSUE THREAD

**Issue by nicecore** [nicecore/project_12_social_team_builder#7]
## Master to-do list

- [x] Use the supplied files as static assets and example templates for your web site.
- [x] Sign up for an account.
- [x] Log into account.
- [x] Log out of account.
- [x] Show profile page.
- [x] Edit profile.
- [x] Upload an avatar for profile.
- [x] Pick my skills for profile.
- [x] Create new projects.
- [x] Show project detail page.
- [x] Create new Positions for project via project detail page.
- [x] Able to apply for a position in a project.
- [x] Able to see all applicants for my project's positions.
- [x] Able to approve an applicant for a position in a project.
- [x] Able to reject an applicant for a position in a project.
- [x] Notifications for rejection/approval for a position.
- [x] Able to search for projects based on words in their titles or descriptions.
- [x] Filter projects by the positions they need filled.
